Add odoo 14 version in installation
resolve this erreur

root@systemerp-prod:/home/sysadmin# systemctl status odoo
× odoo.service - Odoo Open Source ERP and CRM
     Loaded: loaded (/lib/systemd/system/odoo.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2025-07-28 16:58:18 UTC; 5min ago
    Process: 26618 ExecStart=/usr/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log (code=exited, status=1/FAILURE)
   Main PID: 26618 (code=exited, status=1/FAILURE)
        CPU: 235ms
Jul 28 16:58:18 systemerp-prod odoo[26618]:     from . import db, graph, loading, migration, module, registry
Jul 28 16:58:18 systemerp-prod odoo[26618]:   File "/usr/lib/python3/dist-packages/odoo/modules/graph.py", line 10, in <module>
Jul 28 16:58:18 systemerp-prod odoo[26618]:     import odoo.tools as tools
Jul 28 16:58:18 systemerp-prod odoo[26618]:   File "/usr/lib/python3/dist-packages/odoo/tools/init.py", line 17, in <module>
Jul 28 16:58:18 systemerp-prod odoo[26618]:     from .mail import *
Jul 28 16:58:18 systemerp-prod odoo[26618]:   File "/usr/lib/python3/dist-packages/odoo/tools/mail.py", line 35, in <module>
Jul 28 16:58:18 systemerp-prod odoo[26618]:     allowed_tags = clean.defs.tags | frozenset('article bdi section header footer hgroup nav aside figure main'.split() + [etree.Comment])
Jul 28 16:58:18 systemerp-prod odoo[26618]: AttributeError: module 'lxml.html.clean' has no attribute 'defs'
Jul 28 16:58:18 systemerp-prod systemd[1]: odoo.service: Main process exited, code=exited, status=1/FAILURE
Jul 28 16:58:18 systemerp-prod systemd[1]: odoo.service: Failed with result 'exit-code'.